Feature/timestamps
RoboTeamTwente/roboteam_embedded_messages pull request #20
Opened 2023-12-07 14:12 UTC by JWillegers

Changing timestamp to unix timestamp in centiseconds.
This allows for the packets saved on the SD card to be traced back to real world time.
The unit centiseconds was chosen to be precise enough (being able to run at 100Hz) but also use a minimal amount of bytes.

Also changed the generator such that uint64_t to be decode correctly in .h files

2023-12-07 15:27 UTC, emielsteerneman requested changes

2023-12-07 15:27 UTC, emielsteerneman commented on generator/Generator.py
> +						type_cast = "(uint32_t) "
Should be placed within the `C_Generator` class if you want to be consistent

2023-12-07 15:27 UTC, emielsteerneman commented on generator/Generator.py
> +						type_cast = "(uint32_t) "
This feels weird to me since the system is already 32 bits. Should not be needed

2023-12-08 09:23 UTC, JWillegers commented on generator/Generator.py
> +						type_cast = "(uint32_t) "
It is needed.

Before the changes the timestamp looks like this, corresponding to Dec 07 2023 14:26:10: 
![image](https://github.com/RoboTeamTwente/roboteam_embedded_messages/assets/61787386/3479406d-554e-4efb-855c-94b7fadd2df7) 
from [REM_Robotfeedback before changes.csv](https://github.com/RoboTeamTwente/roboteam_embedded_messages/files/13612275/REM_Robotfeedback.before.changes.csv)

After your suggested changes the timestamps looks like this, corresponding to a date in 2317:
![image](https://github.com/RoboTeamTwente/roboteam_embedded_messages/assets/61787386/2c5df2ef-6f97-4df5-b633-c54e053fe726)
from [REM_RobotFeedback after change.csv](https://github.com/RoboTeamTwente/roboteam_embedded_messages/files/13612290/REM_RobotFeedback.after.change.csv)

2023-12-08 09:47 UTC, emielsteerneman commented on generator/Generator.py
> +						type_cast = "(uint32_t) "
Still not sure why it is needed exactly but alright if it works, it works.

2023-12-08 10:08 UTC, JWillegers commented on generator/Generator.py
> +						type_cast = "(uint32_t) "
Resolved in commit c187413

2023-12-08 10:18 UTC, emielsteerneman approved these changes
lgtm

2023-12-13 12:34 UTC, merged